### ISSUE TITLE
Cannot set properties of null (setting 'encoding') in chrome and  i is null in firefox - all your zip have that issue

### ISSUE THREAD

**Issue by johnfelipe** [Misterblue/oar-site#2]
https://gltf-viewer.donmccurdy.com/

unoptimized
[banderas.zip](https://github.com/Misterblue/oar-site/files/8790279/banderas.zip)

smallassets
[banderas (1).zip](https://github.com/Misterblue/oar-site/files/8790281/banderas.1.zip)

mergedmaterials
[banderas (2).zip](https://github.com/Misterblue/oar-site/files/8790283/banderas.2.zip)

![SNAG-1087](https://user-images.githubusercontent.com/428820/170805205-8fda0d48-c797-4748-81fb-99ec51c072e4.png)

This is log of console in chrome:

[gltf-viewer.donmccurdy.com-1653702862293.log](https://github.com/Misterblue/oar-site/files/8790285/gltf-viewer.donmccurdy.com-1653702862293.log)

in firefox:
![SNAG-1088](https://user-images.githubusercontent.com/428820/170805270-dd0f7ee4-c7af-4b19-98fc-33d53c8fa994.png)
log firefox:

[console-export-2022-5-27_20-56-2.txt](https://github.com/Misterblue/oar-site/files/8790288/console-export-2022-5-27_20-56-2.txt)

**Comment by Misterblue** [comment]
This is a bug in generating the zip files -- it is not including the images. There is also a bug in Basil in that, if there are no images, it gives a null reference exception.
I have fixed gen/run.sh to include the images in future zip files.
